[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.83.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview.environment]
HUGO_VERSION = "0.83.1"

[[redirects]]
from = '/api/*'
to = '/.netlify/functions/api/:splat'
status = 200

[functions]
node_bundler = 'esbuild'
