---
label: testimonials
hide_body: true
fields:
- type: field_group_list
  name: testimonial
  label: testimonial
  fields:
  - type: text
    name: effect
    label: effect
  - type: file
    name: image
    label: image
  - type: text
    name: title
    label: title
  - type: textarea
    name: content
    label: content
